-- Oracle script that creates an ASCIIPIC user and geneerate the project database.
-- You should run it as administrator. 


DROP USER ASCIIPIC CASCADE;
CREATE USER ASCIIPIC IDENTIFIED BY ASCIIPIC DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
ALTER USER ASCIIPIC QUOTA 2000M ON USERS;
GRANT CONNECT TO ASCIIPIC;
GRANT CREATE TABLE TO ASCIIPIC;
GRANT CREATE VIEW TO ASCIIPIC;
GRANT CREATE SEQUENCE TO ASCIIPIC;
GRANT CREATE TRIGGER TO ASCIIPIC;
GRANT CREATE SYNONYM TO ASCIIPIC;
GRANT CREATE PROCEDURE TO ASCIIPIC;
