FROM matei10/asciipic_db:latest

MAINTAINER Matei-Marius Micu <micumatei@gmail.com>
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y git
RUN git clone https://github.com/micumatei/asciipic.git
CMD vi

